In [1]:
import numpy as np

In [5]:
# Creating an Arrays
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1),(4,5,6)]], dtype = float)
print(a)
print(b)
print(c)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [9]:
# Placeholders initial
np.zeros((3,4)) # Create an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((2,3,4),dtype=np.int16) # create an array of one

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [12]:
d=np.array((10,25,5),dtype=np.int16) # create an array of evenly spaced values
print(d)

[10 25  5]


In [13]:
np.linspace(0,2,9) #create an array of evenly spaced values(num of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [14]:
e = np.full((2,2),7) # create a constant array
print(e)

[[7 7]
 [7 7]]


In [15]:
f = np.eye(2) # create a 2x2 identity matrix
print(f)

[[1. 0.]
 [0. 1.]]


In [16]:
np.random.random((2,2)) # Create an array with random values

array([[0.8542515 , 0.49441361],
       [0.50056   , 0.1905766 ]])

In [17]:
np.empty((3,2)) # Create an empty array

array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

In [19]:
#Saving and loading on Disk
np.save('my_array',a)
np.savez('array.npz',a,b)
#np.load('my_array.npz')


In [22]:
#Saving and Loading Text Files
#np.loadtxt("myfile.txt")
#np.genfromtxt("my_file.csv",delimter=",")
#np.savetxt("myarray.txt",a,delimter=" ")

# Inspecting Your Array

In [24]:
a.shape #array dimensions
len(a)

3

In [25]:
b.ndim #Number of array dimensions
e.size #traditional len of array
b.dtype # number of array dimensions
b.dtype.name
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

# Data type

In [33]:
np.int64 # signed
np.float32 # standard double precision floating point
#np.complex #depreciated
#np.bool #boolean type storing TRUE and FALSE values
#np.object #python object type
#np.string_ #fixed length string type
#np.unicode_ #fixed length unicode type

numpy.float32

# Array Mathematics

In [35]:
# arithmetic operations
g = a-b #subtraction
print(g)

[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


In [36]:
np.subtract(a,b) # subtraction

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [37]:
b+a #addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [38]:
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [39]:
a/b # Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [40]:
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [41]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [42]:
a*b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [43]:
np.exp(b) #exponential

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [44]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [45]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [46]:
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [47]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [48]:
e.dot(f)

array([[7., 7.],
       [7., 7.]])

In [54]:
# comparision
a=b # element-wise comparision

In [51]:
print(a)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [52]:
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [55]:
a<2

array([[ True, False, False],
       [False, False, False]])

In [56]:
np.array_equal(a,b)

True

In [57]:
#Aggregate functions
a.sum()
a.min()
b.min(axis=0)
b.cumsum(axis=1)
a.mean()
b.median()
a.corrcoef()
np.std(b)

AttributeError: 'numpy.ndarray' object has no attribute 'median'

# Copying Arrays

In [58]:
h = a.view() # create a view of the array with the same data
np.copy(a) # create a copy of the array
h = a.copy() # create a deep copy of the arrays

# Sorting Arrays

In [62]:
a.sort() #sort an array
c.sort(axis=0) #sort the element of an array's axis

# Subsetting,slicing,indexing

In [69]:
#subsetting
x=np.array([1,2,3])
print(x[2])

3


In [70]:
b[1,2]

6.0

In [71]:
#slicing
a[0:2]

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [74]:
b[0:2,1]

array([2., 5.])

In [75]:
b[:1]

array([[1.5, 2. , 3. ]])

In [76]:
c[1,...]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [78]:
x[ : : -1]

array([3, 2, 1])

In [79]:
#boolean Indexing
a[a<2]

array([1.5])

In [80]:
#Fancy Indexing
b[[1,0,1,0],[0,1,2,0]]

array([4. , 2. , 6. , 1.5])

In [81]:
b[[1,0,1,0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

# Array Manipulation

In [83]:
# Transposing Array
i = np.transpose(b)
# or
i.T 

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [85]:
# Changing Array Shape
b.ravel()


array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [92]:
print(a)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [93]:
print(a.shape(3,2))

TypeError: 'tuple' object is not callable

In [95]:
# Adding/Removing elements
h.resize((2,6))
np.append(h,g)
np.insert(a,1,5)
np.delete(a,[1])

array([1.5, 3. , 4. , 5. , 6. ])

In [100]:
#Combining Array
np.concatenate((a,b),axis=0)

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [101]:
np.vstack((a,b)) #stack arrays verticaly(row-wise)

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [102]:
np.r_[e,f] #stack arrays vertically(row-wise)

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [103]:
np.hstack((e,f)) #stack array horizontally

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [105]:
np.column_stack((a,b)) #create stacked column-wise arrays

array([[1.5, 2. , 3. , 1.5, 2. , 3. ],
       [4. , 5. , 6. , 4. , 5. , 6. ]])

In [107]:
np.c_[a,b] # create stacked column-wise arrays

array([[1.5, 2. , 3. , 1.5, 2. , 3. ],
       [4. , 5. , 6. , 4. , 5. , 6. ]])

In [108]:
# splitting arrays
np.hsplit(a,3)

[array([[1.5],
        [4. ]]),
 array([[2.],
        [5.]]),
 array([[3.],
        [6.]])]

In [109]:
np.vsplit(c,2)

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 3.],
         [4., 5., 6.]]])]